import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {getServerSession, redirectIfNoSession} from '../../utils/auth';
import {AntdRegistry} from '@ant-design/nextjs-registry';
import {ReactNode} from "react";
import {redirect} from "next/navigation";

const inter = Inter({subsets: ["latin"]});

interface ProfileLayoutProps {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({children}: Readonly<ProfileLayoutProps>) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <AntdRegistry>
            {children}
        </AntdRegistry>
        </body>
        </html>
    );
}
